version: '3'

services:
    php:
        image: flusio_php:dev
        build:
            context: .
            dockerfile: Dockerfile.php
        restart: unless-stopped
        command: php -t ./public/ -S 0.0.0.0:8000 ./public/index.php
        ports:
            - "8000:8000"
        volumes:
            - ..:/var/www/html:z
            - composer:/tmp
        environment:
            - SEED
            - MOCK_HOST=http://mock_server:8001
        user: $USER
        links:
            - database
            - mock_server

    job_worker:
        image: flusio_php:dev
        build:
            context: .
            dockerfile: Dockerfile.php
        restart: unless-stopped
        command: php cli jobs watch
        volumes:
            - ..:/var/www/html:z
            - composer:/tmp
        user: $USER
        links:
            - database

    mock_server:
        image: flusio_php:dev
        build:
            context: .
            dockerfile: Dockerfile.php
        restart: unless-stopped
        command: php -t . -S 0.0.0.0:8001 ./tests/mock_server.php
        ports:
            - "8001:8001"
        volumes:
            - ..:/var/www/html:z
        user: $USER

    database:
        image: postgres:13-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"

    bundler:
        image: flusio_node:dev
        build:
            context: .
            dockerfile: Dockerfile.node
        restart: unless-stopped
        command: npm run watch
        working_dir: /app
        volumes:
            - ..:/app:z
        user: $USER

volumes:
    composer: {}
