version: '3'

services:
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ..:/var/www/html:z
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:z
        networks:
            default:
                aliases:
                    - mock-server

    php:
        image: flusio_php:dev
        build:
            context: .
            dockerfile: Dockerfile.php
        restart: unless-stopped
        ports:
            - "9000:9000"
        volumes:
            - ..:/var/www/html:z
            - composer:/tmp
        environment:
            - SEED
            - MOCK_HOST=http://mock-server
        user: $USER
        depends_on:
            - nginx
            - database
        networks:
            - default

    job_worker:
        image: flusio_php:dev
        build:
            context: .
            dockerfile: Dockerfile.php
        restart: unless-stopped
        command: php cli jobs watch
        volumes:
            - ..:/var/www/html:z
            - composer:/tmp
        user: $USER
        depends_on:
            - database
        networks:
            - default

    database:
        image: postgres:12-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        networks:
            - default

    bundler:
        image: flusio_node:dev
        build:
            context: .
            dockerfile: Dockerfile.node
        restart: unless-stopped
        command: npm run watch
        working_dir: /app
        volumes:
            - ..:/app:z
        user: $USER

volumes:
    composer: {}

networks:
    default:
